### ISSUE TITLE
Violin Visualization

### ISSUE THREAD

**Issue by rowrowrowrow** [jeetee/MuseScore_Violin_Fingering#1]
Hey @jeetee,

I ran across this and was wondering if you knew whether or not it is possible to create a visualizer of the notes on a violin in musescore. E.g. something like what you would see in this video: https://www.youtube.com/watch?v=Q6ExFKLvVyg. I'm not familiar with musescore enough to judge but would be interested in contributing this back to the community.

**Comment by jeetee** [comment]
As far as I'm aware, this is currently not possible within MuseScore and even faking a workaround seems like it would need quite a lot of work.
(To be honest, all I did here was revive an older plugin that only worked on MS2 and expanded it based on input from users that know more about violins than I do)

But have a look at https://musescore.org/en/node/48596 (and leave a comment there!) which seems to be the official feature request for something close to what you're looking for.
